### ISSUE TITLE
gpg.mozilla.org fails when using hkps on gpg (GnuPG/MacGPG2) 2.2.3

### ISSUE THREAD

**Issue by milescrabill** [mozilla/gpg.mozilla.org#2]
### Client info:

```
gpg --version
gpg (GnuPG/MacGPG2) 2.2.3
libgcrypt 1.8.1
```

This is the latest version shipped as part of [GPGSuite 2018.1](https://gpgtools.org/).

### Actual result: `gpg: keyserver refresh failed: General error`

Using `gpg --keyserver hkp://gpg.mozilla.org/ --refresh` works as expected.

It would be reasonable to resolve this with "here's a nickel kid, update your `gpg` client" if that fixes things.

**Comment by lhirlimann** [comment]
I'm getting the same results on Linux, @gdestuynder can you take a look? (2.2.6)

**Comment by gdestuynder** [comment]
```
gpg (GnuPG) 2.2.7
libgcrypt 1.8.2
```

No issue:

```
gpg --keyserver hkps://gpg.mozilla.org/ --refresh
gpg: refreshing 536 keys from hkps://gpg.mozilla.org/
...
```

ill try to find a way to reproduce

**Comment by gdestuynder** [comment]
after some testing i believe its a behavior of gnutls for older versions of the library. im not exactly sure what causes it, but during session negociation it just bails on the ELB

i run `gnutls 3.5.18` here and i've checked that `gnutls 3.4.10` will fail to contact the server correctly

This changelog might have something that matches though it could be plenty of different things in there: https://fossies.org/linux/gnutls/ChangeLog

**Comment by gdestuynder** [comment]
after some more testing you can fix that for gpg1/g10 by installing `gnupg-curl` (on ubuntu for ex)

for gpg2, i'm still not sure why that triggers:

- gnutls-cli will connect just fine
- dirmngr will not connect (thats what gpg2.1+ uses)

if you want to test (gpg-connect-agent connects to dirmngr just like gpg2 does for keyserver queries):

```
gpg-connect-agent --dirmngr
> keyserver hkps://gpg.mozilla.org
> ks_search gdestuynder@mozilla.com
> keyserver --hosttable
```

This works on a... functional setup. on a non-functional one there is no keyserver in the hosttable at this point

**Comment by gdestuynder** [comment]
via IRC, @milescrabill mentionned that mac gpg updated to 2.2.7 and this fixed it
