### ISSUE TITLE
gpg.mozilla.org is down

### ISSUE THREAD

**Issue by gene1wood** [mozilla/gpg.mozilla.org#7]
Today, I connected to gpg.mozilla.org to free up disk space to get it working again (as the disk had filled).

I connected :

`ssh ec2-user@35.171.190.90`

using the new shared infosec key

I deleted some files

```
rm /var/lib/docker/volumes/gpgmozillaorg_sks/_data/db.log
rm /var/lib/docker/volumes/gpgmozillaorg_sks/_data/merge.log
rm /var/lib/docker/volumes/gpgmozillaorg_sks/_data/recon.log
```

and freed up space but I've been unable to get it working again.

When I start the `recon` service

```
cd /home/ec2-user/gpg.mozilla.org
docker-compose up -d sks-recon
```

it fails with the error

`Fatal error: exception End_of_file`

which can be seen in the logs with

`docker logs gpgmozillaorg_sks-recon_1`

I've overridden the docker entrypoint by adding an entrypoint to the `/home/ec2-user/gpg.mozilla.org/docker-compose.yml` file for the sks-recon docker container (I added an entrypoint of `sleep 600`) and then connected into the container

`docker exec -ti gpgmozillaorg_sks-recon_1 /bin/bash`

and run the command manually

```
cd /var/sks
/usr/bin/sks recon
```

but get the same error. I've been unable to ramp the logging up any further to find what it means.

In looking through the code I can't tell what's causing the problem

https://github.com/cmars/sks-keyserver/search?p=2&q=End_of_file&unscoped_q=End_of_file

I'm leaving the system in this broken state as I can't figure out the problem.

We should either fix this or assemble a plan to retire gpg.mozilla.org given that SKS is now fundamentally broken

https://code.firstlook.media/the-death-of-sks-pgp-keyservers-and-how-first-look-media-is-handling-it

**Comment by lhirlimann** [comment]
I vote on retiring - but you should check if any mozilla services uses it first.

**Comment by gene1wood** [comment]
Indeed, some do.

**Comment by lhirlimann** [comment]
> Indeed, some do.

Reach out and tell them to use something else, whihc means people will have to upload key elsewhere ....

**Comment by gene1wood** [comment]
userplex is switching away from gpg.mozilla.org in mozilla-services/userplex#64
